### ISSUE TITLE
Integration with Yii 1.15

### ISSUE THREAD

**Issue by leowmjw** [mnapoli/PHP-DI#194]
Would like to have example of how to integrate between Yii 1.15 with PHP-DI so that it can be used for legacy projects.  Thanks!

**Comment by marcovtwout** [comment]
After further consideration, creating true DI integration for Yii 1 is too much work. There are more places where components are being constructed (widgets for example) and it is not fully possible without modifying core classes.

Injecting on an application component and calling it only from the high level controllers seems like the most practical solution. Shall I create a separate github project for this component? Any further recommendations?

**Comment by mnapoli** [comment]
@marcovtwout go ahead if you want to!

I'm not sure I understand that:

> Injecting on an application component and calling it only from the high level controllers seems like the most practical solution.

Do you mean extending the application class to add `get()` on it, and call `get()` in controllers?

**Comment by marcovtwout** [comment]
No extending is needed. We add the DI-container as an application component through configuration only (as in the earlier code example). In theory, you can call it from anywhere in the application, but we simply advice users only to call it from the high level controller.

**Comment by marcovtwout** [comment]
Published separately: https://github.com/marcovtwout/yii-php-di

**Comment by mnapoli** [comment]
Awesome thank you!
