### ISSUE TITLE
Namespace conflicts

### ISSUE THREAD

**Issue by tentacode** [mnapoli/PHP-DI#212]
Hello ! I'm using `mnapoli/php-di-symfony2` (php-di 4.2.2) fyi

Imagine I have a `Foo` model entity, which has the same name of my vendor top namespace `Foo` (yeah, weird, but I do have this problem).

```php
<?php

namespace Foo\Something;

use Foo\Model\Foo;

class SomethingElse
{
    /**
     * @Inject
     * @var Foo\Repository\FooRepository $fooRepository
     */
    protected $fooRepository;
}
```

Injects fails because it tries to autoload `Foo\Model\Foo\Repository\FooRepository`

Using `@var \Foo\Repository\FooRepository $fooRepository` would be a solution but it does not work. What can I do my dear @mnapoli ?

**Comment by mnapoli** [comment]
Gonna close this (cleaning up the tracker), reopen if it happens again and hopefully you can get more details
