### ISSUE TITLE
[QUESTION] Is there a way to request a new instance everytime?

### ISSUE THREAD

**Issue by andreigabreanu** [mnapoli/PHP-DI#221]
Basically, is there a way to do something like:

$container->setShared('something', false);

$t1 = $container->get('something');
$t2 = $container->get('something');

echo $t1 === $g2; // Should give FALSE 

ZF2 Service manager allows you to so give a shared key where you can provide a "false" value to each key, where each key is the symbol/class name.

**Comment by mnapoli** [comment]
Hi, yes it's possible with the `prototype` scope: http://php-di.org/doc/scopes.html

```php
return [
    'something' => DI\object()
        ->scope(Scope::PROTOTYPE()),
];
```
