### ISSUE TITLE
Container building takes significantly longer on HHVM than in vanilla PHP

### ISSUE THREAD

**Issue by moberemk** [mnapoli/PHP-DI#227]
So I'm running into weird behavior with HHVM and PHP-DI. Specifically, my container instantiation and subsequent get() calls take a bizarrely long amount of time to execute. I'm measuring this using some basic benchmarks using PHP_Timer on the same codebase running this code on PHP 5.6 and HHVM 5.3:

### Container setup:

    \PHP_Timer::start();
    $builder = new \DI\ContainerBuilder();

    $builder->addDefinitions(APP_PREFIX.'di.php')
            ->useAutowiring(true)
            ->useAnnotations(false); // This is really slow in HHVM. I don't know why.
    echo "Container setup: ".\PHP_Timer::secondsToTimeString(\PHP_Timer::stop())."\n";

### App setup:

    \PHP_Timer::start();
    // Build the request/response objects
    $application = $container->get(\Core\Application::class);

    // Add middleware
    $application->add($container->get(\Middleware\Security::class));
    $application->add($container->get(\Middleware\Router::class));
    echo "App Setup: ".\PHP_Timer::secondsToTimeString(\PHP_Timer::stop())."\n";

### PHP 5.5.1:
Container setup: 20 ms
App Setup: 140 ms

### HHVM:
Container setup: 360 ms
App Setup: 334 ms

I should mention that I'm using a mixed Hack/PHP codebase, but the code which I'm using to test this is pure PHP. and the slowdown is definitely occurring before any Hack code gets involved. I honestly can't identify where the slowdown seems to be occuring. My only real clue at this point is that where HHVM will always hit every registered DefinitionSource, all the way down to ReflectionDefinitionSource, PHP seems to find what it needs up at ArrayDefinitionSource. Which is weird. Any thoughts on why this is happening or even where to start looking for reasons?

**Comment by mnapoli** [comment]
Wow this is indeed really weird.

Have you tried profiling it in both case? e.g. with http://blackfire.io/ or XHprof or whatever. I don't know if there's a profiler for HHVM…

**Comment by moberemk** [comment]
XHProf is baked in to HHVM it seems, so I'll be giving that a shot later
today. Up 'til now I've been doing very rudimentary profiling using echo
statements and PHP_Timer which found that PHP-DI constructs all definitions
for every request in HHVM whereas it only seems to do it for the first
request in 5.5. At least, that's my working theory based on the fact that
HHVM would often go FileDefinitionManager -> ArrayDefinitionManager ->
ReflectionDefinitionManager and then create the definition, whereas PHP
would do the same chain (at the same speed) for the first request and then
go FileDefinitionManager -> ArrayDefinitionManager and end execution.

I find this weird because I don't have any caching implemented currently,
but there must be something being cached that I'm missing.

**Comment by mnapoli** [comment]
And are you using autowiring? Or array definitions in a file? (or maybe a mix?)

**Comment by moberemk** [comment]
Some definitions are in a file returning an array, but for the most part
it's all done via autowiring.

I actually managed to halve the runtime by updating to the latest version
of HHVM, which is a marked improvement, but still extremely long by
comparison.

**Comment by mnapoli** [comment]
OK at least it's going in the right direction.

Wow I just had a quick look at the build times on Travis. Tests run in ~ 1s with PHP, and ~8s with HHVM… That's so weird!

I'm really interested if you have time to do a profiling.

**Comment by moberemk** [comment]
Okay so I've got some basic profiling set up and it seems like a lot of the time for the initial setup is going in to Composer's autoload functionality. Which seems like a really weird (and really bad) place for an issue to be found. It's getting triggered by the use of classnames in the DI definition file actually. I can reduce those calls by rewriting things to use `\Core\HTTP\Request` as a string instead of my original usage of `\Core\HTTP\Request::class` but calling the autoloader doesn't seem to require a ton more processing time and I've found defining using this method to be a faster way of catching typos early. Even then though, it's MAYBE ~10ms of performance gain that I can measure. Doesn't really account for the difference.

I've got the full profile for a single relatively-simple get() request up on Google Drive now (https://docs.google.com/spreadsheets/d/1ZSG9YlwUWxE4VtgGbxy8GQ564pMdNz75ZQE_IB4nEkY/edit?usp=sharing) if you're curious. It's a very simple class which only asks for a reference to the DI container itself via constructor injection.

**Comment by moberemk** [comment]
Some deeper investigation into the profiling reveals two things. First, it runs way slower sometimes but not others, and not in a consistent downwards curve that would match up with how the JIT compilation theoretically operates--we're talking maybe 1/10 runs hit an unexpected slowdown. Deeper examination of the profiling results from a standard run vs a slow run reveals that two primary functions become significantly slower during these runs, specifically `DI\Definition\DefinitionManager::getDefinition==>DI\Definition\Source\ArrayDefinitionSource::getDefinition` and `DI\Definition\Source\ArrayDefinitionSource::getDefinition==>DI\Definition\Source\PHPFileDefinitionSource::getDefinition`, which average out to be about 2.5x as much CPU usage while every other function runs in roughly consistent time during a slower execution. The only other function to have a similar gain is `DI\Definition\Source\PHPFileDefinitionSource::getDefinition==>DI\Definition\Source\PHPFileDefinitionSource::initialize`, which doubles in CPU usage and maintains virtually-identical memory usage stats.

**Comment by mnapoli** [comment]
> Composer's autoload functionality […] is getting triggered by the use of classnames in the DI definition file

Oh that shouldn't happen :/ At least in Zend PHP, `use Foo\Bar` and `Bar::class` are **not** supposed to trigger autoload. I know because if you write a typo (like `$class = Ba::class`) then no error will appear *unless* you try to use `$class`.

I don't know if it's normal that HHVM works differently on this. I searched through HHVM's issue tracker but couldn't find anything about that.

I had a look at the profiling link, thanks for that. What are the time units? micro-s? Is the wall time supposed to include sub-calls or not.

I find really weird that for example `Composer\Autoload\ClassLoader::findFileWithExtension==>file_exists` is so high on the list (it takes `1781` but I don't know what).

And regarding the random slowdowns, wow. I just don't know what to say about that :p

**Comment by moberemk** [comment]
I think HHVM--or maybe Hack+HHVM--may do that differently then. I'll have
to experiment more on that to verify. As for the profiling, I'm using
XHProf to get that data, so wall time includes all sub-calls and is
measured in CPU ticks.

I've been wondering if this might be related to the fact that this is
running on a Vagrant Virtualbox VM. The file functions especially might
take some hits given the virtual linking from VM to host PC, but that's
more of a crazy idea than legitimate theory.

**Comment by mnapoli** [comment]
Ah the Vagrant thing could affect the performances indeed. At least I know it's a very common problem in Symfony, e.g. http://www.whitewashing.de/2013/08/19/speedup_symfony2_on_vagrant_boxes.html

> so wall time includes all sub-calls

OK, I'm using Blackfire lately, but I thought I remembered that in XHprof there was a way to see with sub-call included and excluded? The "excluded" view is useful to see which method actually consumes the most time.

So maybe the additional class loading done by HHVM slows down the app because Vagrant FS is slow?

**Comment by mnapoli** [comment]
Actually it seems [HHVM doesn't trigger autoloading](http://3v4l.org/ske6e), maybe Hack does.

But it's probably [that code](https://github.com/mnapoli/PHP-DI/blob/master/src/DI/Definition/Source/ReflectionDefinitionSource.php#L38) that triggers the autoload anyway (both for PHP and HHVM).

Can you show me the code for your test?

So: slow because of Vagrant? Maybe. But then why is there a difference between PHP and HHVM… Ideally it would be good to have the same code profiled with PHP and HHVM to spot the differences.

**Comment by moberemk** [comment]
That Symfony link's a good resource, yeah; a non-VM HHVM server has just been set up so I'm hoping to benchmark execution time there. I don't have any machines which are running PHP and HHVM though so I haven't been able to directly compare the two. I'll have to do that at some point.

I'm not sure where to get excluded wall time from though; [reading the docs](http://docs.hhvm.com/manual/en/ref.xhprof.php) doesn't seem to suggest that as a flag though, which makes me think that requires a UI I can't seem to access.

**Comment by mnapoli** [comment]
Ah yeah I was using a UI but I don't know which one…

**Comment by mnapoli** [comment]
Should we keep this issue open? Are you still experiencing it and have you been able to dig into it more?

**Comment by moberemk** [comment]
I'm still running in to issues honestly, but I've never been able to
identify what specifically is causing it to run so much slower. It still
runs fast enough for most requests that we've opted to ignore it for the
time being in development and rely on more aggressive cache usage and
beefier servers in production.

I may file an issue with HHVM since it seems compiler-specific.

**Comment by mnapoli** [comment]
OK thanks for the feedback. Yes maybe HHVM people can have a better idea of what's going on
