### ISSUE TITLE
Is it possible to make Proxy Manager a suggest instead of a requirement?

### ISSUE THREAD

**Issue by mvriel** [mnapoli/PHP-DI#228]
Hi @mnapoli,

During an installation of PHP-DI using composer I noticed that 'ocramius/proxy-manager' is being installed, which brings the dependencies `zendframework/zend-code`, `zendframework/zend-eventmanager`, `zendframework/zend-stdlib`.

As far as I can see I do not need those dependencies because I am not using the proxy functionality; would it make sense to move the `ocramius/proxy-manager` to the require-dev or suggests so that it is not added by default?

**Comment by mnapoli** [comment]
Hey @mvriel, glad to know you are giving this package a try!

It's planned and implemented in (future) v5 (see #198). The pull request for v5 is in #200 if you are curious.

**Comment by mvriel** [comment]
Looking good! I am curious: what timeframe are you thinking of with version 5 and is it stable enough to try out in a new project?

**Comment by mnapoli** [comment]
I wouldn't say it's stable, even though we are using it in [Piwik](https://github.com/piwik/piwik). The idea is to test features with a real life use case and have the liberty to adjust. Once it's stable, v5 will be released. But I think there might be some changes coming (not 100% sure yet) so if I were you I wouldn't.

The main thing of v5 is support for modular systems (i.e. like Symfony bundles, where modules can extend the base config and override each others). If you don't need that, then v4 should definitely be good enough. And the upgrade path to v5 will be fairly easy and documented.

There is not really a timeframe, it could be in 1 month or up to 3-4 :)

**Comment by mvriel** [comment]
The project on which I am working isn't in a hurry and what you describe does sound appealing; I might give it a try knowing that you will be changing things. That modular systems change, is that already done? I couldn't find docs in the PR so I want to know before I go searching in the sourcecode ;)

**Comment by mnapoli** [comment]
That's interesting! Maybe you'll have feedback to give also on those new features.

Regarding documentation, I think you can find everything in the separate issues. Those features are mainly about inheriting definitions and extending definitions (needed for a modular system), and they are mainly discussed in #214. It's quite a read, but I'm very interested in your feeling about it if you do read it. Most of it is *not* implemented yet.

A smaller issue about string definitions: #224 (implemented)

Also some "syntactic sugar" that I documented in a blog post: http://php-di.org/news/14-php-di-5-syntaxic-sugar.html That is all implemented in the branch except #208 (nested definitions).

The main BC break I'm considering for v5 is this: right now object definitions automatically extend each-other. For example in file A you define an object, and in file B you change one constructor parameter value. The main reason for this feature being the default is to allow simple integration between autowiring, annotations and file configs… E.g. if you have:

```php
public function __construct(LoggerInterface $logger, $dbHost)
```

You can do only this in the config file:

```php
return [
     'MyClass' => DI\object()
        ->constructorParameter('dbHost', 'localhost');
];
```

(no need to define again the `$logger` parameter)

That's cool, but it has some problems, and I'm considering making the default different:

- by default, definitions override any previous definition (i.e. file definition would completely override the "autowiring" definition)
- you can optionally choose to extend/decorate the previous definition (that requires to explicitly do it)

That behavior would then be consistent across all definition types. See [this comment](https://github.com/mnapoli/PHP-DI/issues/214#issuecomment-67068742) for the detailed arguments.

What do you feel about this change and the related BC break?

**Comment by mnapoli** [comment]
If you do start using v5, let me know I'll try to think about you if I push anything that might break. But except the BC break I just detailed, the rest should be pretty stable.

Also will you have very high performance expectations on your application? In most cases the container is just a fraction of the request so it's no problem but just so you know this branch is not benchmarked or optimized yet.

**Comment by mnapoli** [comment]
Ohh is that [this](https://github.com/somos/framework)? That readme sounds super interesting, if you need any help regarding PHP-DI ping me in your project I'll be glad to help! (or you can open an issue here too)

**Comment by mvriel** [comment]
You are absolutely, right! I am trying out PHP-DI 5 in Somos as I believe that Somos will take quite some time for it to be ready enough for beta and that means that with any luck PHP-DI 5 will be launched by then :)

And don't worry about breaks because I am trying it out; I am aware I am using experimental / development releases. I have the same thing going with phly/http

**Comment by mnapoli** [comment]
Awesome good luck!

**Comment by mnapoli** [comment]
Just a FYI regarding https://github.com/somos/framework/issues/31 (didn't want to derail the topic so I'm posting here), PHP-DI offers [a `call()` method](http://php-di.org/doc/container.html) that works a bit like AngularJS:

```php
$parameters = [
    'data' => /* some variable */
];

$container->call(function (Logger $logger, $data) {
    // ...
}, $parameters);
```

Beyond allowing to inject dependencies at will, it's also a good way to invoke stuff without having to implement it again. In the issue you mention the ability to define business logic as a closure, or an invokable object, or also the class name as a string (which will be resolved using the container): PHP-DI can do that with `call()`.

It gives an interesting solution: you can then use DI both in classes (traditional way with constructor parameters) but also in action callables. That means you can write actions as closures and still benefit from DI even though you don't have a constructor/state. And you can mix injecting services with injecting request parameters (matching is done first by type-hint to find a service, then by argument name).

I've used that in a (not-serious) micro-framework I built to show that feature: https://github.com/mnapoli/minimal-app#dependency-injection-in-controller-actions

Maybe it will give you ideas who knows!

**Comment by mvriel** [comment]
That does sounds interesting! Thank you for sharing that as it will simplify the code that I am currently writing.

Does it also support this use-case?

```
class MyAction
{
    public function __construct(MyDependency $dependency)
    {
        ...
    }

    public function indexAction(Request $request)
    {
        ...
    }

    public function showAction(Request $request)
    {
        ...
    }
}
```

```
$di->call('MyAction::indexAction');
```

Also: do I understand correctly that in your example the data field in the array $parameters is injected into $data because the name matches?

**Comment by mnapoli** [comment]
`MyAction::indexAction` is actually the only PHP callable format that isn't supported ;) ([see this comment](https://github.com/mnapoli/PHP-DI/pull/173#issuecomment-50620876)). I wouldn't have a problem with adding support for that though, I just didn't bother at the time because using the array notation is much more PHP 5.5 friendly with `::class`:

    use Super\Long\Namespace\MyAction;

    $container->call([MyAction::class, 'indexAction']);

**Comment by mvriel** [comment]
The version that you wrote will try to invoke a static method indexAction instead of constructing an object first; or will PHP-DI create / retrieve an object if it doesn't find a static method?

**Comment by mnapoli** [comment]
If it's a static method, it will just call the static method.

If it's an object method, it will resolve the object using the container.

PS: I've updated my comment above with more info.

**Comment by mvriel** [comment]
Awesome! You don't have to change any behaviour then; I will alter the text of https://github.com/somos/framework/issues/31 to match this

**Comment by mvriel** [comment]
One last thing! 

> Also: do I understand correctly that in your example the data field in the array $parameters is injected into $data because the name matches?

Is this true?

**Comment by mnapoli** [comment]
> Also: do I understand correctly that in your example the data field in the array $parameters is injected into $data because the name matches?

Yes exactly. It can match for 2 reasons:

- the type-hint == a container entry name (which are usually class names when you use autowiring) -> this is dependency injection
- the parameter name == the name of an item of the array -> this is just `call_user_func_array` behavior

I use it e.g. to do something like this:

```php
$controller = function (LoggerInterface $logger, $name) {
    // $name is the same as $_GET['name']
}

$container->call($controller, $_GET + $_POST);
```

The only problem with that is that it's impossible to inject a container entry that is not indexed by the class name (because you can't type-hint it). I haven't found a clean way to do that yet, except introducing a new array:

```php
$container->set('logger.log_file_name', '/tmp/app.log');

$controller = function ($logFile, $name) {
}

$containerEntriesMapping = [
    'logFile' => 'logger.log_file_name'
];

$container->call($controller, $_GET, $containerEntriesMapping);
```

2 arrays for similar yet different stuff, quite confusing… So I don't really know about that.

**Comment by mvriel** [comment]
@mnapoli in an earlier comment (https://github.com/mnapoli/PHP-DI/issues/228#issuecomment-74369161) you talked about breaking BC because Object references now extend by default; I am totally ok with that break. In fact: I like it.

It feels intuitive for me to override entries if you redefine them and extending an object should be an explicit action. That just makes sense to me (perhaps because I am used to Pimple?)

**Comment by mnapoli** [comment]
:+1: I think all other containers behave that way (at least those that have a way to override/extend definitions).

Thanks for the feedback.
