### ISSUE TITLE
Mixing containers and annotations

### ISSUE THREAD

**Issue by wdalmut** [mnapoli/PHP-DI#229]
Hi,

it is possible to mixing containers and using other container definitions with PHP-DI annotations? For example having services defined into Symfony2 containers and use `Inject` annotation in order to inject a service into an object?

```php
<?php
class MyClass
{
    /**
     * @Inject 
     * @var manager
     */
    private $prop;
}
```

Symfony container services

```xml
<service id="manager" class="NewsletterManager">
   ...
</service>
```
I am trying with Acclimate and the `get` operation works correctly but not with annotations can different containers chained? 

```php
<?php
$acclimate = new ContainerAcclimator;

$container = new CompositeContainer();
$container->addContainer($acclimate->acclimate($sfContainer));

$builder = new ContainerBuilder();
$builder->wrapContainer($container);

$phpdiContainer = $builder->build();
$container->addContainer($acclimate->acclimate($phpdiContainer));
```

Walter

**Comment by wdalmut** [comment]
I discovered that i can't using aliases with Inject annotations but if i prepare a container and setting the id with the fully qualified name of an object it works...

```xml
<service id="NewsletterManager" class="NewsletterManager">...</service>
```

```php
<?php
class MyClass
{
    /**
     * @Inject NewsletterManager
     */
    private $prop;
}
```

**Comment by wdalmut** [comment]
Ok,

all works fine, the var annotation effectively is a common PHPDoc comment for real things. We can use 

```
/**
 * @Inject("manager")
 */
private $prop;
```

For aliases.

**Comment by mnapoli** [comment]
Yes you figured it out! Sorry I was on holidays.

But instead of using Acclimate directly I suggest you use the official Symfony 2 integration: http://php-di.org/doc/frameworks/symfony2.html

Cheers!

**Comment by wdalmut** [comment]
i am playing around with components from different open-source projects in order to design something particular https://github.com/wdalmut/frankie a frankenstein microframework because uses different components and a particular brain labeled:  "Do Not Use This Brain! Abnormal"  :smile: What do you think about it, any advice?

**Comment by mnapoli** [comment]
hey that's awesome, really fun!

You'll get a lot of hate from people that hate annotations, but whatever, this is an idea to try out! It seems pretty cool for RAD.

**Comment by wdalmut** [comment]
Yeah, you're right, effectively i am reaching people that really enjoy it and others that hates it! But it is  interesting discussing about annotations and other stuffs for php.

Thanks again
Walter
