### ISSUE TITLE
Add support for AOP techniques

### ISSUE THREAD

**Issue by joshdifabio** [mnapoli/PHP-DI#230]
Have you considered implementing support for AOP techniques? Specifically, providing support for method interception (call `foo()` `before`, `after`, or `around` `bar()`) would be extremely helpful.

This might be outside of the scope of what you want to do with PHP-DI, but since the technical requirements for method interception overlap those of PHP-DI so much it might be worth considering.

**Comment by joshdifabio** [comment]
For clarity, here are a couple of possible usage examples.

__Log all DB queries__
```php
Db::class => DI\object()->before('execute', function (Db $subject, $sql) use ($container) {
    $container->get('logger.db')->debug($sql);
}),
```

__Log any exceptions which occur during DB query execution__
```php
Db::class => DI\object()->around('execute', function (Db $subject, \Closure $execute, $sql) use ($container) {
    try {
        return $execute($sql);
    } catch (\Exception $e) {
        $container->get('logger.db')->error($e);
        throw $e;
    }
}),
```

**Comment by mnapoli** [comment]
Thanks for the suggestion!

This is something I considered a few years back, but today I'm convinced it shouldn't be part of PHP-DI. As you said, it's outside of the scope of a DI container.

But as you said again, the DI container provides a technical solution to implement AOP, so why not leave the door open for a separate package to implement it by integration with PHP-DI?

However, I don't think using a DI container to do this is the best approach for several reasons:

- unless you go through some complex challenges, proxying objects would only work with `DI\object()` definitions (e.g. not with `DI\factory()`, etc...)… That would be confusing and restrictive
- you could only do AOP on "services", but not on other classes of your application (e.g. model entities, or actually anything that you don't instantiate through PHP-DI), that's restrictive and confusing
- it would probably not be the fastest solution

If I were to do AOP I would probably go down the road of a [PHP extension](https://github.com/AOP-PHP/AOP), or maybe [go-aop-php](https://github.com/lisachenko/go-aop-php). At least I could use it on any object, and the PHP extension would be faster.

**Comment by joshdifabio** [comment]
Thanks for the reply, Matthieu. I agree with your points; I'll close this issue :).
