### ISSUE TITLE
Container::make should allow to override container entries

### ISSUE THREAD

**Issue by moberemk** [mnapoli/PHP-DI#231]
I'll admit that I'm probably doing something wrong here but....here's what I'm trying to do:

    $this->container->make(PGC::class, ['db_name' => $data['db']]);

where the definition looks something like this:

    \Database\PGC::class => \DI\factory(function(Container $c) {
        return new \Database\PGC($c->get('db_host'), $c->get('db_user'), $c->get('db_pass'), $c->get('db_name'));
    })

Now, the problem here is that, well, the get call will get whatever the container current holds as the `db_name` value. Which works fine except for when I want it to be called via make, where I have no way of getting at that overriden parameter.

I'm honestly not sure what the nice way of handling this would be, but having some way of getting at the specified parameters in the factory function would be nice, maybe as a function argument passed to the factory function?

**Comment by mnapoli** [comment]
Yes `make()` takes an array of values to inject by the parameter name.

I realize this feature is not documented well enough, and people are often confused. I should probably improve this.

Here is an example:

```php
class Foo {
    public function __construct(LoggerInterface $logger, $filename) {...}
}
```

In that situation, parameters passed to `make()` need to match the name of the parameters:

```php
$container->make(PGC::class, [
    'logger' => new ...,
    'filename' => '',
]);
```

The array values are not meant to override container entries.

It's not the first time someone tries to override container entries, so I think I will keep this issue open and try to find a solution for v5.

**Comment by moberemk** [comment]
Yeah I realize it's not really intended behaviour, but this isn't the first
time I've wanted to use value injection this way. To get around this I've
been thinking I'll need to define some sort of config container object (or
since I'm using Hack, more likely a shape) to pass in to this object given
the number of settings it requires.

Actually, that's probably a cleaner solution than finding a way to coerce
configuration variables into the `make()` method. It might be better not to
allow overriding of factory functions because I honestly can't think of a
way to pass that in given what I know of current PHP-DI architecture.

**Comment by mnapoli** [comment]
Yes after thinking about it I'm not sure either it's a good idea to allow that. I'll update the documentation though to make it clear how this feature works and what it allows. Thanks.
