### ISSUE TITLE
No entry or class found (for two or more definition sources)

### ISSUE THREAD

**Issue by Kilte** [mnapoli/PHP-DI#240]
This is a very serious problem, which I do not know how to solve.

The following code can help to reproduce it:

```php
use DI\Container;
use DI\ContainerBuilder;
use DI\Definition\Source\ArrayDefinitionSource;

class A {
    public function getData()
    {
        return 'data';
    }
}

class B {
    private $data;
    public function __construct($data)
    {
        $this->data = $data;
    }
}

class C {
    private $a;
    public function __construct(A $a)
    {
        $this->a = $a;
    }
}
class D {
    private $a;
    private $b;
    private $params;

    public function __construct(A $a, B $b, $params)
    {
        $this->a = $a;
        $this->b = $b;
        $this->params = $params;
    }
}

$definitions1 = [
// TODO: add some definitions ...
];
$definitions2 = [
    A::class => \DI\object(),
    B::class => \DI\factory(function (Container $c) {
        return new B($c->get(A::class)->getData());
    }),
    C::class => \DI\object()->constructor(\DI\link(A::class)),
    D::class => \DI\factory(function (Container $c) {
        return new D($c->get(A::class), $c->get(B::class), 'params');
    }),
];

$builder = new ContainerBuilder();
$builder->useAutowiring(false);
$builder->useAnnotations(false);
$builder->addDefinitions(new ArrayDefinitionSource($definitions1));
$builder->addDefinitions(new ArrayDefinitionSource($definitions2));
$container = $builder->build();
$c = $container->get(C::class);
$d = $container->get(D::class);

var_dump($c, $d);
```

Output:

```
PHP Fatal error:  Uncaught exception 'DI\NotFoundException' with message 'No entry or class found for 'Example\C'' in /home/kilte/projects/crazyarts/backend/vendor/mnapoli/php-di/src/DI/Container.php:120
Stack trace:
#0 /home/kilte/projects/crazyarts/backend/t.php(63): DI\Container->get('Example\\C')
#1 {main}
  thrown in /home/kilte/projects/crazyarts/backend/vendor/mnapoli/php-di/src/DI/Container.php on line 120
```
I think this problem may be caused by this line: https://github.com/mnapoli/PHP-DI/blob/master/src/DI/Definition/Source/ArrayDefinitionSource.php#L77

**Comment by mnapoli** [comment]
Thank you for the report, I have to admit I don't know why you are getting the exception. I will try to reproduce with your example.

**Comment by mnapoli** [comment]
OK reproduced and I think I've identified the source. I have tried a quick patch like this and it works:

```diff
@@ -57,9 +57,8 @@ class ArrayDefinitionSource implements ChainableDefinitionSource
         if ($definition === null) {
             // Not found, we use the chain or return null
             if ($this->chainedSource) {
-                return $this->chainedSource->getDefinition($name, $parentDefinition);
+                $definition = $this->chainedSource->getDefinition($name, $parentDefinition);
             }
-            return null;
         }
```

I will write correct tests and ensure there is no regression with this fix before releasing it (will do today).

Thanks a lot for reporting that!

**Comment by Kilte** [comment]
Thank you for your quick reply.

**Comment by mnapoli** [comment]
No worries. I'm keeping this issue open until it is fixed to keep track of it

**Comment by mnapoli** [comment]
That wasn't too long actually. I have released [4.4.7](https://github.com/mnapoli/PHP-DI/releases/tag/4.4.7) please give it a try and let me know if all works fine for you!

**Comment by Kilte** [comment]
Everything works fine for me  :+1:. Thanks again.

**Comment by konstantinosDMS** [comment]
I wrote a class Mailer and UserManager as the examples into a project named phpdi. Then I create a test_phpdi page with the following: 
include_once 'vendor/autoload.php';

$container = new DI\Container();
$userManager = $container->get('UserManager');

and I get:
Fatal error: Uncaught DI\NotFoundException: No entry or class found for 'UserManager' in C:\xampp\htdocs\TestProject\phpdi\vendor\php-di\php-di\src\Container.php:134 Stack trace: #0 C:\xampp\htdocs\TestProject\phpdi\test_phpdi.php(6): DI\Container->get('UserManager') #1 {main} thrown in C:\xampp\htdocs\TestProject\phpdi\vendor\php-di\php-di\src\Container.php on line 134

Could you explain me whai is happening on?

**Comment by mnapoli** [comment]
@konstantinosDMS please do not ressuscitate closed issues.

Also please do not post this as an issue, this is support and should go in the chat or StackOverflow (which you already did). You don't need to spam everywhere.
