### ISSUE TITLE
Correct way to inject DateTime ?

### ISSUE THREAD

**Issue by udf2457** [mnapoli/PHP-DI#258]
If I do something like

```
DateTime::class=>DI\Object(\DateTime::class)
My\Toolbox::class=>DI\Object()
                ->constructor(DI\Link('DateTime'))
```

I get 

cannot be resolved: Entry DateTime cannot be resolved: The parameter 'time' of DateTime::__construct has no type defined or guessable. It has a default value, but the default value can't be read through Reflection because it is a PHP internal class.

**Comment by mnapoli** [comment]
The error tells you that you need to define the `time` parameter, e.g.

```php
DateTime::class=>DI\Object(\DateTime::class)
                ->constructor('now')
```

However I *highly* recommend against configuring `DateTime` in the container as it's not a service. If it's a configuration value, you might be better doing something like this:

```php
'default.date.for.something' => new DateTime('now')
```

or use a factory.
